services:
  database:
    container_name: api_spotify_db_postgresql
    image: postgres:latest
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - pgdata:/var/lib/postgresql/data:rw

volumes:
  pgdata: